[package]
name = "phases"
version = "0.1.0"
edition = "2021"

[dependencies]
gif = "0.12.0"
plotters = "0.3.4"
rand = { version = "0.8.5", features = ["small_rng"] }
rand_pcg = "0.3.1"
rand_seeder = "0.2.3"

